# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
require 'faker'

u1 = User.create(name: "Joseph Cha", username: "chacha123", password: "123", bio: "I love to cha cha slide", image_url: "https://ca.slack-edge.com/T02MD9XTF-USM2G2TNV-f854fbc28824-512")
u2 = User.create(name: "Kelly Becker", username: "kelzBeck", password: "123", bio: "I love events sooooo much", image_url: "https://ca.slack-edge.com/T02MD9XTF-URUPJ4A9H-cc8ebbaf4e79-512")
u3 = User.create(name: "Daniel Urbina", username: "danielxurbina", password: "123", bio: "I created this website haha", image_url: "https://ca.slack-edge.com/T02MD9XTF-UTV12LVL6-54082a1d620c-512")
u4 = User.create(name: "Uriel Rodriguez", username: "codenameuriel", password: "123", bio: "Don't mess me with me i'm a software engineer", image_url: "https://ca.slack-edge.com/T02MD9XTF-UTFAJQM51-d8c7ed79404f-512")
u5 = User.create(name: "Andrew Casarsa", username: "andrewcas", password: "123", bio: "I think i'm lowkey obsessed with dogs haha", image_url: "https://ca.slack-edge.com/T02MD9XTF-UTFAJGADR-cf894db2cc40-512")
u6 = User.create(name: "Caryn McCarthy", username: "cmac", password: "123", bio: "I like to yarn in my backyard listening to country", image_url: "https://ca.slack-edge.com/T02MD9XTF-UNF12Q8JE-2b02c06a660d-512")
u7 = User.create(name: "Isabelle Pino", username: "izzybell", password: "123", bio: "I have no clue what's going on but whatever", image_url: "https://ca.slack-edge.com/T02MD9XTF-UC6H2GLG0-5df96d5f1ca6-512")
u8 = User.create(name: "Ethan Fournier", username: "ethan4", password: "123", bio: "“How long are you going to wait before you demand the best for yourself and in no instance bypass the discriminations of reason? You have been given the principles that you ought to endorse, and you have endorsed them. What kind of teacher, then, are you still waiting for in order to refer your self-improvement to him? You are no longer a boy, but a full-grown man. If you are careless and lazy now and keep putting things off and always deferring the day after which you will attend to yourself, you will not notice that you are making no progress, but you will live and die as someone quite ordinary. From now on, then, resolve to live as a grown-up who is making progress, and make whatever you think best a law that you never set aside. And whenever you encounter anything that is difficult or pleasurable, or highly or lowly regarded, remember that the contest is now: you are at the Olympic Games, you cannot wait any longer, and that your progress is wrecked or preserved by a single day and a single event. That is how Socrates fulfilled himself by attending to nothing except reason in everything he encountered. And you, although you are not yet a Socrates, should live as someone who at least wants to be a Socrates.”", image_url: "https://ca.slack-edge.com/T02MD9XTF-UNDSGQY3H-8d8358573e5b-512")
u9 = User.create(name: "Ryan Vaznis", username: "rvaznis", password: "123", bio: "I like to play football and drink beer so what's up man", image_url: "https://ca.slack-edge.com/T02MD9XTF-UTSAYAYS0-1d29f39b322c-512")
u10 = User.create(name: "Jacky Lin", username: "jacky_lin", password: "123", bio: "I like fast cars and I don't mind dying in one", image_url: "https://ca.slack-edge.com/T02MD9XTF-UTUL90AEB-51f029f69ed9-512")



e1 = Event.create(user_id: u1.id, location: "Home", title: "Flatiron School Graduation", date: Faker::Date.forward(days: 30), description: "We get to finally graduate and join our dream job!", image_url: "https://res-4.cloudinary.com/crunchbase-production/image/upload/c_lpad,h_256,w_256,f_auto,q_auto:eco/v1397752768/e4ce735bc7e299313e5ca95eaf86a030.png", price: 0)
e2 = Event.create(user_id: u1.id, location: "Bora Bora" ,title: "Adventure Time!", date: Faker::Date.forward(days: 100), description: "Tired of staying home so let's go to Bora Bora :)", image_url: "https://conradhotels3.hilton.com/resources/media/ch/PPTBNCI/en_US/img/shared/full_page_image_gallery/main/CN_resortext_700x525_FitToBoxSmallDimension_Center.jpg", price: 0)
e3 = Event.create(user_id: u1.id, location: "California" ,title: "Photography Lesson", date: Faker::Date.forward(days: 150), description: "Join me in attending Reuben Wu's awesome photography class!", image_url: "https://lh3.googleusercontent.com/proxy/Y7_pOSdsoWb2SajaIobnBcPZ8vffZu-7DNkan3-RMeCoZLpY0z19UIuikp2HEXsu0uCT55N1hMeCTWZzEe0y0vV9AkfDrZTeiwRjp1wNiO5qHohZerRWKSAP", price: 250)
e4 = Event.create(user_id: u1.id, location: "California" ,title: "Hike and Watch The Clouds", date: Faker::Date.forward(days: 155), description: "There's this super dope spot on top of this mountain, nice view and really chill vibes.", image_url: "https://scene360.com/wp-content/uploads/2015/02/reuben-wu-09.jpg", price: 0)
e5 = Event.create(user_id: u1.id, location: "Monmouth Park" ,title: "Picnic Day", date: Faker::Date.forward(days: 45), description: "Having a Picnic Day with some friends", image_url: "https://images.squarespace-cdn.com/content/v1/55128f03e4b0767ae4f47b54/1553712807051-D43WSR7J5D45UXH4B8GC/ke17ZwdGBToddI8pDm48kFmfxoboNKufWj-55Bgmc-J7gQa3H78H3Y0txjaiv_0fDoOvxcdMmMKkDsyUqMSsMWxHk725yiiHCCLfrh8O1z4YTzHvnKhyp6Da-NYroOW3ZGjoBKy3azqku80C789l0iXS6XmVv7bUJ418E8Yoc1hjuviiiZmrL38w1ymUdqq4JaGeFUxjM-HeS7Oc-SSFcg/JLau-JG-4224.jpg?format=2500w", price: 0)
e6 = Event.create(user_id: u1.id, location: "California" ,title: "Coachella", date: Faker::Date.forward(days: 90), description: "Selling some tickets for Coachella so get them while you still can!", image_url: "https://i1.wp.com/www.coturesocial.com/wp-content/uploads/2018/05/untilnextyearcoachella.jpg", price: 350)
e7 = Event.create(user_id: u2.id, location: "PineWood Social" ,title: "Bowling", date: Faker::Date.forward(days: 37), description: "Bowling day so join us and bring drinks!", image_url: "https://i.pinimg.com/originals/3b/46/2e/3b462eb87adfd8abdd4885fed9f4bc65.jpg", price: 45)
e8 = Event.create(user_id: u2.id, location: "Brooklyn" ,title: "Botanical Garden", date: Faker::Date.forward(days: 65), description: "Explore the botanical garden and reserve your spot today!", image_url: "https://i.pinimg.com/originals/47/8f/46/478f46232a175c83c6c0e9f4f362eb1f.jpg", price: 35)
e9 = Event.create(user_id: u3.id, location: "Madison Square Garden" ,title: "The 1975 Concert", date: Faker::Date.forward(days: 100), description: "The 1975 playing at the Madison Square Garden! Don't miss out and get your tickets today as they're starting to sell out fast!", image_url: "https://wallpapercave.com/wp/wp4689567.jpg", price: 750)
e10 = Event.create(user_id: u3.id, location: "Madison Square Garden" ,title: "Coldplay Concert", date: Faker::Date.forward(days: 150), description: "Coldplay are coming to Madison Square Garden! It's something you don't want to miss so get your tickets today!", image_url: "https://static.billboard.com/files/media/coldplay-performs-in-Sydney-dec-2016-billboard-1548-1024x677.jpg", price: 600)
e11 = Event.create(user_id: u4.id, location: "Calabria" ,title: "Selling my house", date: Faker::Date.forward(days: 200), description: "Selling my house in Calabria as I don't live there anymore. If anyone is interested in buying it let me know! Contact number is 862-555-3453.", image_url: "https://www.roughguides.com/wp-content/uploads/2012/11/amalfi-italy-shutterstock_759048709.jpg", price: 9000)
e12 = Event.create(user_id: u4.id, location: "Paris" ,title: "Vist the Eiffel Tower", date: Faker::Date.forward(days: 90), description: "Vist the Eiffel Tower today! 5 more tickets left so don't miss out. It includes the full package that has 2 round trip tickets, a place to stay by the Eiffel Tower, and yes food will be provided. If interested contact me at my email - uriel@gmail.com ", image_url: "https://cdn.lifestyleasia.com/wp-content/uploads/2019/10/21224220/Winer-Parisienne.jpg", price: 1200)
e13 = Event.create(user_id: u5.id, location: "Montclair" ,title: "Brunch at Coffee House", date: Faker::Date.forward(days: 30), description: "Come to our grand opening where we will be serving our finest brunch options, you won't regret it!", image_url: "https://www.instagram.com/p/BomFbebD4fw/media?size=l", price: 0)
e14 = Event.create(user_id: u5.id, location: "UCLA" ,title: "UCLA vs Utah", date: Faker::Date.forward(days: 70), description: "Come watch UCLA play against the Utah Utes.", image_url: "https://img.bleacherreport.net/img/images/photos/003/093/376/b7cacd7fc5a8e821b9587d480cb2cb12_crop_north.jpg?1412490571&w=3072&h=2048", price: 45)
e15 = Event.create(user_id: u6.id, location: "Miami" ,title: "Learn How to Produce", date: Faker::Date.forward(days: 120), description: "Learn how to produce with Jim Morris, a producer that worked with artists such as Jay Z, Kanye West, and many more! It's a once in a million opportunity, don't miss out!", image_url: "https://i.pinimg.com/originals/a6/98/a0/a698a0a05318d6753c67635c32b9a7ae.jpg", price: 450)
e16 = Event.create(user_id: u6.id, location: "New York" ,title: "Learn how to Code", date: Faker::Date.forward(days: 50), description: "I'm a lead instructor at Flatiron School and I decided to do some personal tutoring to those who want to learn how to code!", image_url: "https://cdn.educba.com/academy/wp-content/uploads/2016/01/web-designing.jpg", price: 75)
e17 = Event.create(user_id: u7.id, location: "Jersey City" ,title: "Babysit", date: Faker::Date.forward(days: 50), description: "I have a date coming up soon and I need someone to take care of my dog while i'm away. If you're interested contact me at 973-432-9521.", image_url: "https://i.ytimg.com/vi/wRx3Uvcktm8/maxresdefault.jpg", price: 100)
e18 = Event.create(user_id: u8.id, location: "Boston" ,title: "Selling my Vintage Car", date: Faker::Date.forward(days: 27), description: "I need quick money and I hate to sell this car but I have no other choice. It's a 1972 Ford Consul in prestine condition so I won't take small amounts, but I will be reasonable too. If you're interested contact me at 201-555-3232", image_url: "https://i.pinimg.com/originals/f7/46/01/f7460172ba55bdca9ed1f7a1d70dd697.jpg", price: 150000)
e19 = Event.create(user_id: u9.id, location: "Connecticut" ,title: "Hot Air Balloon Ride", date: Faker::Date.forward(days: 90), description: "Come join us on a ride and bring some fun drinks as we will be flying through the skies exploring.", image_url: "https://i.pinimg.com/originals/f3/29/4a/f3294a42cb54d7f929096846bf752f85.jpg", price: 75)
e20 = Event.create(user_id: u10.id, location: "New Jersey" ,title: "Lantern Festival", date: Faker::Date.forward(days: 45), description: "Sky Lantern Festival coming to you soon! Buy your tickets now to reserve your spot.", image_url: "https://i.pinimg.com/originals/0d/d9/3e/0dd93e30c4c05defe2523596f38528bf.jpg", price: 35)


j1 = JoinedEvent.create(user_id: u1.id, event_id: e7.id)
j2 = JoinedEvent.create(user_id: u1.id, event_id: e10.id)
j3 = JoinedEvent.create(user_id: u1.id, event_id: e11.id)
j4 = JoinedEvent.create(user_id: u1.id, event_id: e12.id)
j5 = JoinedEvent.create(user_id: u1.id, event_id: e13.id)
j6 = JoinedEvent.create(user_id: u1.id, event_id: e14.id)
j7 = JoinedEvent.create(user_id: u1.id, event_id: e17.id)
j8 = JoinedEvent.create(user_id: u1.id, event_id: e20.id)